version: "3"
services:
  db:
    image: postgres:12.9
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPassword 
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: